name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r messaging_app/requirements.txt

    - name: Run tests
      run: |
        python manage.py test

            - name: Lint with flake8
        pip install flake8
        flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
        coverage xml
        mkdir -p coverage-reports
        cp coverage.xml coverage-reports/

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-reports/coverage.xml

